//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pets.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult.
        /// </summary>
        internal static string awl_age_adult {
            get {
                return ResourceManager.GetString("awl_age_adult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senior.
        /// </summary>
        internal static string awl_age_senior {
            get {
                return ResourceManager.GetString("awl_age_senior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Young.
        /// </summary>
        internal static string awl_age_young {
            get {
                return ResourceManager.GetString("awl_age_young", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Energy.
        /// </summary>
        internal static string awl_lifestyle_high {
            get {
                return ResourceManager.GetString("awl_lifestyle_high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Energy.
        /// </summary>
        internal static string awl_lifestyle_low {
            get {
                return ResourceManager.GetString("awl_lifestyle_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium Energy.
        /// </summary>
        internal static string awl_lifestyle_medium {
            get {
                return ResourceManager.GetString("awl_lifestyle_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWL - Edinburgh North Shelter.
        /// </summary>
        internal static string awl_location_AWL___Edinburgh_North_Shelter {
            get {
                return ResourceManager.GetString("awl_location_AWL - Edinburgh North Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWL - Wingfield Shelter.
        /// </summary>
        internal static string awl_location_AWL___Wingfield_Shelter {
            get {
                return ResourceManager.GetString("awl_location_AWL - Wingfield Shelter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For Pet&apos;s Sake.
        /// </summary>
        internal static string awl_location_For_Pet_s_Sake {
            get {
                return ResourceManager.GetString("awl_location_For Pet\'s Sake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETstock - Allenby Gardens.
        /// </summary>
        internal static string awl_location_PETstock___Allenby_Gardens {
            get {
                return ResourceManager.GetString("awl_location_PETstock - Allenby Gardens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETstock - Melrose Park.
        /// </summary>
        internal static string awl_location_PETstock___Melrose_Park {
            get {
                return ResourceManager.GetString("awl_location_PETstock - Melrose Park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETstock - Munno Para.
        /// </summary>
        internal static string awl_location_PETstock___Munno_Para {
            get {
                return ResourceManager.GetString("awl_location_PETstock - Munno Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETstock - Noarlunga.
        /// </summary>
        internal static string awl_location_PETstock___Noarlunga {
            get {
                return ResourceManager.GetString("awl_location_PETstock - Noarlunga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PETstock - Parafield.
        /// </summary>
        internal static string awl_location_PETstock___Parafield {
            get {
                return ResourceManager.GetString("awl_location_PETstock - Parafield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        internal static string awl_sex_female {
            get {
                return ResourceManager.GetString("awl_sex_female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        internal static string awl_sex_male {
            get {
                return ResourceManager.GetString("awl_sex_male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string awl_size_large {
            get {
                return ResourceManager.GetString("awl_size_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string awl_size_medium {
            get {
                return ResourceManager.GetString("awl_size_medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string awl_size_small {
            get {
                return ResourceManager.GetString("awl_size_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopted.
        /// </summary>
        internal static string awl_status_adopted {
            get {
                return ResourceManager.GetString("awl_status_adopted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string awl_status_available {
            get {
                return ResourceManager.GetString("awl_status_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopted.
        /// </summary>
        internal static string awl_status_gone {
            get {
                return ResourceManager.GetString("awl_status_gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string awl_type_Cat {
            get {
                return ResourceManager.GetString("awl_type_Cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        internal static string awl_type_Dog {
            get {
                return ResourceManager.GetString("awl_type_Dog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit.
        /// </summary>
        internal static string awl_type_Rabbit {
            get {
                return ResourceManager.GetString("awl_type_Rabbit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Hendon.
        /// </summary>
        internal static string rspca_location_107 {
            get {
                return ResourceManager.GetString("rspca_location_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Mile End.
        /// </summary>
        internal static string rspca_location_108 {
            get {
                return ResourceManager.GetString("rspca_location_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Universe Broadview.
        /// </summary>
        internal static string rspca_location_126 {
            get {
                return ResourceManager.GetString("rspca_location_126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semaphore Vet Clinic.
        /// </summary>
        internal static string rspca_location_127 {
            get {
                return ResourceManager.GetString("rspca_location_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main North Road Vet Service.
        /// </summary>
        internal static string rspca_location_145 {
            get {
                return ResourceManager.GetString("rspca_location_145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adelaide Animal Hospital.
        /// </summary>
        internal static string rspca_location_149 {
            get {
                return ResourceManager.GetString("rspca_location_149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prospect Road Vet.
        /// </summary>
        internal static string rspca_location_151 {
            get {
                return ResourceManager.GetString("rspca_location_151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Noarlunga.
        /// </summary>
        internal static string rspca_location_158 {
            get {
                return ResourceManager.GetString("rspca_location_158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aldinga Vet Services.
        /// </summary>
        internal static string rspca_location_160 {
            get {
                return ResourceManager.GetString("rspca_location_160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hills Veterinary Centre.
        /// </summary>
        internal static string rspca_location_161 {
            get {
                return ResourceManager.GetString("rspca_location_161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Prospect.
        /// </summary>
        internal static string rspca_location_165 {
            get {
                return ResourceManager.GetString("rspca_location_165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Holden Hill.
        /// </summary>
        internal static string rspca_location_178 {
            get {
                return ResourceManager.GetString("rspca_location_178", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Elizabeth.
        /// </summary>
        internal static string rspca_location_186 {
            get {
                return ResourceManager.GetString("rspca_location_186", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Norwood.
        /// </summary>
        internal static string rspca_location_187 {
            get {
                return ResourceManager.GetString("rspca_location_187", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petbarn Melrose Park.
        /// </summary>
        internal static string rspca_location_198 {
            get {
                return ResourceManager.GetString("rspca_location_198", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lonsdale Shelter.
        /// </summary>
        internal static string rspca_location_21 {
            get {
                return ResourceManager.GetString("rspca_location_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whyalla Shelter.
        /// </summary>
        internal static string rspca_location_22 {
            get {
                return ResourceManager.GetString("rspca_location_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Lincoln Shelter.
        /// </summary>
        internal static string rspca_location_23 {
            get {
                return ResourceManager.GetString("rspca_location_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string rspca_status_3 {
            get {
                return ResourceManager.GetString("rspca_status_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopted.
        /// </summary>
        internal static string rspca_status_gone {
            get {
                return ResourceManager.GetString("rspca_status_gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        internal static string rspca_type_1 {
            get {
                return ResourceManager.GetString("rspca_type_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string rspca_type_14 {
            get {
                return ResourceManager.GetString("rspca_type_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitten.
        /// </summary>
        internal static string rspca_type_15 {
            get {
                return ResourceManager.GetString("rspca_type_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puppy.
        /// </summary>
        internal static string rspca_type_16 {
            get {
                return ResourceManager.GetString("rspca_type_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cattle.
        /// </summary>
        internal static string rspca_type_18 {
            get {
                return ResourceManager.GetString("rspca_type_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheep.
        /// </summary>
        internal static string rspca_type_19 {
            get {
                return ResourceManager.GetString("rspca_type_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cat.
        /// </summary>
        internal static string rspca_type_2 {
            get {
                return ResourceManager.GetString("rspca_type_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goat.
        /// </summary>
        internal static string rspca_type_21 {
            get {
                return ResourceManager.GetString("rspca_type_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dog.
        /// </summary>
        internal static string rspca_type_3 {
            get {
                return ResourceManager.GetString("rspca_type_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fowl.
        /// </summary>
        internal static string rspca_type_4 {
            get {
                return ResourceManager.GetString("rspca_type_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rodent.
        /// </summary>
        internal static string rspca_type_73 {
            get {
                return ResourceManager.GetString("rspca_type_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pig.
        /// </summary>
        internal static string rspca_type_74 {
            get {
                return ResourceManager.GetString("rspca_type_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string rspca_type_76 {
            get {
                return ResourceManager.GetString("rspca_type_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reptile.
        /// </summary>
        internal static string rspca_type_79 {
            get {
                return ResourceManager.GetString("rspca_type_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab/Fish.
        /// </summary>
        internal static string rspca_type_83 {
            get {
                return ResourceManager.GetString("rspca_type_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amphibian.
        /// </summary>
        internal static string rspca_type_84 {
            get {
                return ResourceManager.GetString("rspca_type_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guinea Pig.
        /// </summary>
        internal static string rspca_type_85 {
            get {
                return ResourceManager.GetString("rspca_type_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rabbit.
        /// </summary>
        internal static string rspca_type_86 {
            get {
                return ResourceManager.GetString("rspca_type_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferret.
        /// </summary>
        internal static string rspca_type_93 {
            get {
                return ResourceManager.GetString("rspca_type_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bird.
        /// </summary>
        internal static string rspca_type_98 {
            get {
                return ResourceManager.GetString("rspca_type_98", resourceCulture);
            }
        }
    }
}
